[workspace]
members = [
    "crates/*",
]
resolver = "2"

[workspace.package]
version = "0.0.1-snapshot"
authors = ["Niklas Jungnitz <git@jungnik.org>"]
license = "MIT"
edition = "2021"

[workspace.dependencies]
egg = "0.10.0"
libc = "0.2"
paste = "1.0"
seq-macro = "0.3.5"
