[package]
name = "eggmock"
version = "0.0.1-alpha"
authors = ["Niklas Jungnitz <git@jungnik.org>"]
license = "MIT"
edition = "2021"

[dependencies]
egg = "0.10.0"
libc = "0.2"
paste = "1.0"
seq-macro = "0.3.5"
indoc = "2.0.5"
