[package]
name = "eggmock-example-mig"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[workspace]

[dependencies]
eggmock = { path = "../../../crates/eggmock" }

[build-dependencies]
eggmock = { path = "../../../crates/eggmock" }
