[package]
name = "mig-rewrite-rs"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
eggmock = { path = "../../.." }

[build-dependencies]
eggmock = { path = "../../.." }
