[package]
name = "eggmock"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
egg = { workspace = true }
libc = { workspace = true }
paste = { workspace = true }
seq-macro = { workspace = true }